apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-unifi.fullname" . }}
  labels:
    {{- include "tkf-docker-unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: remote-syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
    - name: http-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https-8443
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: http-8880
      port: 8880
      targetPort: 8880
      protocol: TCP
    - name: https-8843
      port: 8843
      targetPort: 8843
      protocol: TCP
    - name: speedtest-6789
      port: 6789
      targetPort: 6789
      protocol: TCP
    - name: localdb
      port: 27117
      targetPort: 27117
      protocol: TCP
    {{- range untilStep 5656 5699 1 }}
    - name: port-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
    {{- end }}
    - name: port-10001
      port: 10001
      targetPort: 10001
      protocol: UDP
    - name: port-1900
      port: 1900
      targetPort: 1900
      protocol: UDP
  selector:
    {{- include "tkf-docker-unifi.selectorLabels" . | nindent 4 }}
