apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "calibre-web.fullname" . }}
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "calibre-web.fullname" . }}
  selector:
    matchLabels:
      {{- include "calibre-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calibre-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calibre-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-calibre"
            - name: TZ
              value: "{{ .Values.calibreWeb.TZ }}"
            - name: PUID
              value: "{{ .Values.calibreWeb.puid }}"
            - name: PGID
              value: "{{ .Values.calibreWeb.pgid }}"
          volumeMounts:
            - name: calibreconfig
              mountPath: /config
            - name: calibremedia
              mountPath: /books
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: calibremedia
          nfs:
            server: {{ .Values.persistence.calibreMedia.server | quote }}
            path: {{ .Values.persistence.calibreMedia.path | quote }}
  volumeClaimTemplates:
    - metadata:
        name: calibreconfig
      spec:
        accessModes:
          - {{ .Values.persistence.calibreConfig.accessModes }}
        storageClassName: {{ .Values.persistence.calibreConfig.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.calibreConfig.size | quote }}
