apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tkf-docker-mariadb.fullname" . }}
  labels:
    app: {{ template "tkf-docker-mariadb.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  my.cnf: |-
{{ .Values.mysqlConfiguration | indent 4 }}
