apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tkf-docker-mariadb.fullname" . }}
  labels:
    app: {{ template "tkf-docker-mariadb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "tkf-docker-mariadb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-docker-mariadb.selectorLabels" . | nindent 8 }}
        app: {{ template "tkf-docker-mariadb.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.containerEnv.tz }}"
            - name: PUID
              value: "{{ .Values.containerEnv.puid}}"
            - name: PGID
              value: "{{ .Values.containerEnv.pgid}}"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "tkf-docker-mariadb.fullname" . }}
                  key: mariadb-root-password
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /config/
      volumes:
        - name: config
          configMap:
            name: {{ template "tkf-docker-mariadb.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "tkf-docker-mariadb.name" . }}-config
