apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tkf-docker-mariadb.fullname" . }}
  labels:
    {{- include "tkf-docker-mariadb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tkf-docker-calibre-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-docker-calibre-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "tkf-docker-mariadb.fullname" . }}
                  key: mariadb-root-password
            - name: MARIADB_USER
              value: {{ default "" .Values.mariadbUser | quote }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "tkf-docker-mariadb.fullname" . }}
                  key: mariadb-password
            - name: MARIADB_DATABASE
              value: {{ default "" .Values.mariadbDatabase | quote }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
              initialDelaySeconds: 5
              timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/
        volume:
          - name: config
            configMap:
              name: {{ template "tkf-docker-mariadb.fullname" . }}
          - name: data
          {{- if .Values.persistance.enabled }}
            persistanceVolumeClaim:
              claimName: {{ template "tkf-docker-mariadb.fullname" . }}
          {{- else }}
            emptyDir: {}
          {{- end -}}