apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tkf-docker-mariadb.fullname" . }}
  labels:
    {{- include "tkf-docker-mariadb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "tkf-docker-mariadb.fullname" . }}
      {{- include "tkf-docker-mariadb.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-docker-mariadb.selectorLabels" . | nindent 8 }}
        app: {{ include "tkf-docker-mariadb.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: PUID
            value: "1001"
          - name: PGID
            value: "1001"
          - name: TZ
            value: "America/Denver"
          - name: MYSQL_ROOT_PASSWORD
            value: FOOBAR
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /config
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "tkf-docker-mariadb.name" . }}-config

