apiVersion: v1
kind: Service
metadata:
  name: {{ template "tkf-docker-mariadb.fullname" . }}
  labels:
    app: {{ template "tkf-docker-mariadb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port:  3306
    protocol: TCP
    targetPort: 3306
  type: ClusterIP
  selector:
    app: {{ template "tkf-docker-mariadb.fullname" . }}
