apiVersion: v1
kind: Service
metadata:
  name: {{ template "tkf-docker-mariadb.fullname" . }}
  labels:
    {{- include "tkf-docker-mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port:  {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "tkf-docker-mariadb.selectorLabels" . | nindent 4 }}