# Default values for tkf-docker-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

updateStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

podAnnotations: {}
podLabels: {}

securityContext:
  enabled: true
  runAsUser: 1001
  fsGroup: 1001

image:
  registry: docker.io
  repository: registry
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.7.1"
  ## Specify an imagePull Policy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ##
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: ""
  tls:
    secretName: docker-svcs-teknofile-space-tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the follow/ng
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  accessMod: 'ReadWriteOnce'
  enabled: true
  size: 10Gi
  deleteEnabled: true

service:
  port: 5000

dnsName: docker.svcs.teknofile.space

nfs:
  nfsPath: "/mnt/tkfstorage/docker/registry"
  nfsServer: "tkf-nas-02.cosprings.teknofile.net"
  
secrets:
  htpasswd: ""