# Default values for tkf-docker-heimdall.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

updateStrategy: {}
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 1
#    maxUnavailable: 0

podLabels: {}

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001

image:
  registry: docker.io
  repository: teknofile/tkf-docker-sonarr
  pullPolicy: "Always"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ingress:
  enabled: true
  className: ""
  tls:
    secretName: heimdall-ctn-tls

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  accessMode: 'ReadWriteOnce'
  enabled: true
  size: 10Gi

dnsName: heimdall.cosprings.teknofile.net
nfs:
#  configServer: "tkf-nas-02.cosprings.teknofile.net"
#  configPath: "/mnt/tkfstorage/docker/tkf-heimdall"
  configServer: "tkf-nas-01.cosprings.teknofile.net"
  configPath: "/c/sonarr"
  mediaServer: "tkf-nas-02.cosprings.teknofile.net"
  mediaPath: "/mnt/tkfstorage/media/TV Shows"
#  nzbgetServer: "tkf-nas-01.cosprings.teknofile.net"
#  nzbgetPath: "/c/nzbget"
  nzbgetServer: "tkf-nas-02.cosprings.teknofile.net"
  nzbgetPath: "/mnt/tkfstorage/media/nzbget"

service:
  port: 80

containerEnv:
  tz: "America/Denver"
  puid: 1001
  pgid: 1001
