# Default values for tkf-docker-lum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: teknofile/tkf-docker-lum
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  dnsName: lum.example.org
  tlsSecretName: certSecret-tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is the secret that has the cert to

service:
  port: 80

containerEnv:
  tz: "America/Denver"
  ldap_admins_group: "admins"
  ldap_admin_bind_dn: "cn=admin,dc=example,dc=org"
  ldap_admin_bind_pwd: "changeme"
  ldap_base_dn: "dc=example,dc=org"
  ldap_ignore_cert_errors: true
  ldap_require_starttls: true
  ldap_uri: "ldap://ldap1.example.org"
  server_name: "lum.example.org"
  email_domain: "example.org"
  # 
  # These are "Optional" - see https://github.com/wheelyubird/ldap-user-manager
  #
  # server_hostname: "ldapusername.org"
  # organisation_name: "LDAP"
  # site_name: Change this to replace the title in the menu, e.g. "Myu Company Account Management"
  # ldap_user_ou
  # ldap_group_ou
  # ldap_tls_cacert
  # LDAP_ACCOUNT_ATTRIBUTE
  # LDAP_GROUP_MEMBERSHIP_ATTRIBUTE
  # LDAP_ACCOUNT_ADDITIONAL_OBJECTCLASSES
  # LDAP_ACCOUNT_ADDITIONAL_ATTRIBUTES
  # LDAP_GROUP_MEMBERSHIP_USES_UID
  # FORCE_RFC2307BIS
  # DEFAULT_USER_GROUP
  # 
  # DEFAULT_USER_SHELL
  # EMAIL_DOMAIN
  # ENFORCE_SAFE_SYSTEM_NAMES
  # USERNAME_FORMAT
  # USERNAME_REGEX
  # PASSWORD_HASH
  # ACCEPT_WEAK_PASSWORDS
