apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "heimdall.fullname" . }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - heimdall.cosprings.teknofile.net
    secretName: tkf-global-wildcard-tls
  rules:
    - host: heimdall.cosprings.teknofile.net
      http:
        paths:
          - backend:
              service:
                name: {{ include "heimdall.fullname" . }}
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific