apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tkf-docker-lum.fullname" . }}
  labels:
    app: {{ template "tkf-docker-lum.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "tkf-docker-lum.name" . }}
      release: {{ .Release.Name }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "tkf-docker-lum.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: "{{ .Values.containerEnv.tz }}"
            - name: LDAP_ADMINS_GROUP
              value: "admins"
            - name: LDAP_ADMIN_BIND_DN
              value: "cn=admin,dc=cosprings,dc=teknofile,dc=net"
            - name: LDAP_ADMIN_BIND_PWD
              value: "changeme"
            - name: LDAP_BASE_DN
              value: "dc=cosprings,dc=teknofile,dc=net"
            - name: LDAP_IGNORE_CERT_ERRORS
              value: "TRUE"
            - name: LDAP_REQUIRE_STARTTLS
              value: "TRUE"
            - name: LDAP_URI
              value: "ldap://ldap1.cosprings.teknofile.net"
            - name: SERVER_NAME
              value: "lum.cosprings.teknofile.net"
            - name: EMAIL_DOMAIN
              value: "teknofile.net"