apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-lum.fullname" . }}
  labels:
    {{- include "tkf-docker-lum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "tkf-docker-lum.name" . }}
