apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tkf-nzbget.fullname" . }}
  labels:
    {{- include "tkf-nzbget.labels" . | nindent 4 }}
spec:
  replicas:  {{ .Values.replicaCount }}
  serviceName: {{ include "tkf-nzbget.fullname" . }}
  selector:
    matchLabels:
      {{- include "tkf-nzbget.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-nzbget.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tkf-nzbget.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6789
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6789
          readinessProbe:
            tcpSocket:
              port: 6789
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: "{{ .Values.nzbget.TZ }}"
            - name: PUID
              value: "{{ .Values.nzbget.puid }}"
            - name: PGID
              value: "{{ .Values.nzbget.pgid }}"
            - name: NZBGET_USER
              value: "{{ .Values.nzbget.username }}"
            - name: NZBGET_PASS
              value: "{{ .Values.nzbget.password }}"
          volumeMounts:
            - name: nzbgetconfig
              mountPath: /config
            - name: nzbgetdownloads
              mountPath: /downloads
            - name: config-volume
              mountPath: /config/nzbget.conf
              subPath: nzbget.conf
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "tkf-nzbget.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: nzbgetconfig
      spec:
        accessModes:
          - {{ .Values.persistence.nzbgetconfig.accessModes }}
        storageClassName: {{ .Values.persistence.nzbgetconfig.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.nzbgetconfig.size | quote }}
    - metadata:
        name: nzbgetdownloads
      spec:
        accessModes:
          - {{ .Values.persistence.nzbgetdownloads.accessModes }}
        storageClassName: {{ .Values.persistence.nzbgetdownloads.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.nzbgetdownloads.size | quote }}