apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-codeserver.fullname" . }}
  labels:
    {{- include "tkf-codeserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "tkf-codeserver.selectorLabels" . | nindent 4 }}
