# Default values for tkf-docker-mariadb
#

image: 
  tag: latest
  registry: docker.io
  repository: teknofile/tkf-docker-mariadb

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
imagePullPolicy: Always

## Specify password for root user
## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
##
# mariadbRootPassword:

## Create a database user
## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
##
# mariadbUser:
# mariadbPassword:

## Create a database
## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-on-first-run
##
# mariadbDatabase:

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  accessMode: 'ReadWriteOnce'
  size: 10Gi

## Configure MariaDB with a custom my.cnf file
## ref: https://mariadb.com/kb/en/mariadb/configuring-mariadb-with-mycnf/#example-of-configuration-file
##
# config: |-
  # [mysqld]
  # innodb_buffer_pool_size=2G

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 250m

nodeSelector: {}

mysqlConfiguration: |-
  [mysqld]
  skip-name-resolve
  basedir=/opt/tkf/mariadb
  plugin_dir=/opt/tkf/mariadb
  port=3306
  socket=/opt/tkf/mariadb/tmp/mysql.sock
  tmpdir=/opt/tkf/mariadb/tmp
  max_allowed_packet=16M
  bind-address=0.0.0.0
  pid-file=/opt/tkf/mariadb/tmp/mysqld.pid
  log-error=/opt/tkf/mariadb/logs/mysqld.log
  character-set-server=UTF8
  collation-server=utf8_general_ci

  [client]
  port=3306
  socket=/opt/tkf/mariadb/tmp/mysql.sock
  default-character-set=UTF8
  plugin_dir=/opt/tkf/mariadb/plugin

  [manager]
  port=3306
  socket=/opt/tkf/mariadb/tmp/mysql.sock
  pid-file=/opt/tkf/mariadb/tmp/mysqld.pid

nfs:
  configServer: "tkf-nas-01.cosprings.teknofile.net"
  configPath: "/c/dckr-mariadb"

containerEnv:
  tz: "America/Denver"
  puid: "1001"
  pgid: "1001"
  mysqlRootPassword: CHANGEME
