apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tkf-docker-plex.fullname" . }}
  labels:
    {{- include "tkf-docker-plex.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tkf-docker-plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-docker-plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tkf-docker-plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: plex
              containerPort: 32400
              protocol: TCP
            - name: plex-for-roku
              containerPort: 8324
              protocol: TCP
            - name: plex-dlna
              containerPort: 32469
              protocol: TCP
            - name: plex-dlna-udp
              containerPort: 1900
              protocol: UDP
            - name: bonjour-avahi
              containerPort: 5353
              protocol: UDP
            - name: gdm1
              containerPort: 32410
              protocol: UDP
            - name: gdm2
              containerPort: 32412
              protocol: UDP
            - name: gdm3
              containerPort: 32413
              protocol: UDP
            - name: gdm4
              containerPort: 32414
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /tv
              name: plex-tv
            - mountPath: /movies
              name: plex-movies
          env:
            - name: PLEX_CLAIM
              value: {{ .Values.plex.claim }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: plex-config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-docker-plex.name" . ) }}-config 
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: plex-tv
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-docker-plex.name" . ) }}-tv 
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: plex-movies
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-docker-plex.name" . ) }}-movies
          {{- else }}
          emptyDir: {}
          {{- end }}
