{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "tkf-docker-plex.name" . }}-config
  labels:
    app: {{ template "tkf-docker-plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.nfs.enabled }}
  nfs:
    path: {{ .Values.persistence.nfs.configPath }}
    server: {{ .Values.persistence.nfs.configServer }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ template "tkf-docker-plex.name" . }}-config
{{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "tkf-docker-plex.name" . }}-tv
  labels:
    app: {{ template "tkf-docker-plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.nfs.enabled }}
  nfs:
    path: {{ .Values.persistence.nfs.tvPath }}
    server: {{ .Values.persistence.nfs.tvServer }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ template "tkf-docker-plex.name" . }}-tv
{{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "tkf-docker-plex.name" . }}-movies
  labels:
    app: {{ template "tkf-docker-plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.nfs.enabled }}
  nfs:
    path: {{ .Values.persistence.nfs.moviesPath }}
    server: {{ .Values.persistence.nfs.moviesServer }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ template "tkf-docker-plex.name" . }}-movies
{{- end }}