apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-gogs.fullname" . }}
  labels:
    {{- include "tkf-docker-gogs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      name: gogs-http
  selector:
    app: {{ template "tkf-docker-gogs.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-gogs.fullname" . }}-ssh
  labels:
    {{- include "tkf-docker-gogs.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      name: gogs-ssh
  selector:
    app: {{ template "tkf-docker-gogs.name" . }}
