apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tkf-ghost.fullname" . }}
  labels:
    {{- include "tkf-ghost.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "tkf-ghost.fullname" . }}
  selector:
    matchLabels:
      {{- include "tkf-ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-ghost.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tkf-ghost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 2368
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 2368
          readinessProbe:
            tcpSocket:
              port: 2368
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ghost
              mountPath: /var/lib/ghost/content
          env:
            - name: URL
              value: "https://www.teknofile.org/"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ghost-config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-ghost.name" . ) }}-config
          {{- else }}
          emptyDir: {}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: ghost
      spec:
        accessModes:
          - {{ .Values.persistence.accessModes }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
