apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-radarr.fullname" . }}
  labels:
    {{- include "tkf-radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: radarr
  selector:
    {{- include "tkf-radarr.selectorLabels" . | nindent 4 }}