apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-opensearch.fullname" . }}
  labels:
    app.kubernetes.io/component: opensearch
    {{- include "tkf-opensearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: elasticsearch
      port: {{ .Values.service.ports.elasticsearch }}
      targetPort: elasticsearch
      protocol: TCP
    - name: esperf
      port: {{ .Values.service.ports.esperf }}
      targetPort: esperf
      protocol: TCP
  selector:
    {{- include "tkf-opensearch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch