apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "docker-registry.name" . }}
  namespace: default
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.dnsName }}
