apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-svcs-teknofile-space
  namespace: default
spec:
  secretName: docker-svcs-teknofile-space-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.dnsName }}
