apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "docker-registry.name" . }}-secure
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.dnsName }}`)
    kind: Rule
    services:
    - name: {{ template "docker-registry.name" . }}
      port: 5000
  tls:
    secretName: docker-svcs-teknofile-space-tls