apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-secure
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.dnsName }}`)
    kind: Rule
    services:
    - name: tkf-docker-registry
      port: 5000
  tls:
    secretName: docker-svcs-teknofile-space-tls
