apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-registry.fullname" . }}
  labels:
    {{- include "tkf-docker-registry.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "tkf-docker-registry.selectorLabels" . | nindent 4 }}
