apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "tkf-docker-heimdall.name" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{.Values.dnsName }}`)
      kind: Rule
      services:
        - name: {{ template "tkf-docker-heimdall.name" . }}
          port: 80
