apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tkf-docker-radarr.fullname" . }}
  labels:
    {{- include "tkf-docker-radarr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tkf-docker-radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-docker-radarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tkf-docker-radarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7878
          livenessProbe:
            httpGet:
              path: /
              port: 7878
          readinessProbe:
            httpGet:
              path: /
              port: 7878
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-media
              mountPath: /tv
            - name: radarr-nzbget
              mountPath: /downloads
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: radarr-config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-docker-radarr.name" . ) }}-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: radarr-nzbget
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-docker-radarr.name" . ) }}-nzbget
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: radarr-media
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tkf-docker-radarr.name" . ) }}-media
          {{- else }}
          emptyDir: {}
          {{- end }}