apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-radarr.fullname" . }}
  labels:
    {{- include "tkf-docker-radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 7878
  selector:
    {{- include "tkf-docker-radarr.selectorLabels" . | nindent 4 }}