apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tkf-readarr.fullname" . }}
  labels:
    {{- include "tkf-readarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "tkf-readarr.fullname" . }}
  selector:
    matchLabels:
      {{- include "tkf-readarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-readarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tkf-readarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: readarr
              containerPort: 8787
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8787
          readinessProbe:
            tcpSocket:
              port: 8787
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: "{{ .Values.readarr.TZ }}"
            - name: PUID
              value: "{{ .Values.readarr.puid }}"
            - name: PGID
              value: "{{ .Values.readarr.pgid }}"
          volumeMounts:
            - name: readarrconfig
              mountPath: /config
            - name: readarrmedia
              mountPath: /books
            - name: readarrnzbget
              mountPath: /downloads
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: readarrmedia
          nfs:
            server: {{ .Values.persistence.readarrMedia.server | quote }}
            path: {{ .Values.persistence.readarrMedia.path | quote }}
        - name: readarrnzbget
          {{- if .Values.persistence.readarrNzbget.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.readarrNzbget.existingClaim | default (include "tkf-readarr.name" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: readarrconfig
      spec:
        accessModes:
          - {{ .Values.persistence.readarrConfig.accessModes }}
        storageClassName: {{ .Values.persistence.readarrConfig.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.readarrConfig.size | quote }}
