{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "tkf-mongodb.fullname" . }}
  namespace: {{ .Release.Namespace . | quote }}
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "tkf-mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
    storageClass: {{ .Values.persistence.storageClass | quote }}
{{- end }}