apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tkf-radarr.fullname" . }}
  labels:
    {{- include "tkf-radarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "tkf-radarr.fullname" . }}
  selector:
    matchLabels:
      {{- include "tkf-radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tkf-radarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tkf-radarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: radarr
              containerPort: 7878
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 7878
          readinessProbe:
            tcpSocket:
              port: 7878
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: radarrconfig
              mountPath: /config
            - name: radarrmedia
              mountPath: /tv
            - name: radarrnzbget
              mountPath: /downloads
          env:
            - name: TZ
              value: "{{ .Values.radarr.TZ }}"
            - name: PUID
              value: "{{ .Values.radarr.puid }}"
            - name: PGID
              value: "{{ .Values.radarr.pgid }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: radarrmedia
          nfs:
            server: {{ .Values.persistence.radarrMedia.server | quote }}
            path: {{ .Values.persistence.radarrMedia.path | quote }}
        - name: radarrnzbget
          {{- if .Values.persistence.radarrNzbget.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.radarrNzbget.existingClaim | default (include "tkf-radarr.name" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: radarrconfig
      spec:
        accessModes:
          - {{ .Values.persistence.radarrConfig.accessModes }}
        storageClassName: {{ .Values.persistence.radarrConfig.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.radarrConfig.size | quote }}