{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "tkf-docker-piwigo.name" . }}
  labels:
    app: {{ template "tkf-docker-piwigo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.nfs.enabled }}
  nfs:
    path: {{ .Values.persistence.nfs.configPath }}
    server: {{ .Values.persistence.nfs.configServer }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ template "tkf-docker-piwigo.name" . }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "tkf-docker-piwigo.name" . }}-gallery
  labels:
    app: {{ template "tkf-docker-piwigo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.nfs.enabled }}
  nfs:
    path: {{ .Values.persistence.nfs.galleryPath }}
    server: {{ .Values.persistence.nfs.galleryServer }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ template "tkf-docker-piwigo.name" . }}-gallery
{{- end }}
{{- end }}