apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-sonarr.fullname" . }}
  labels:
    {{- include "tkf-sonarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: sonarr
  selector:
    {{- include "tkf-sonarr.selectorLabels" . | nindent 4 }}