apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ template "tkf-docker-calibre-web.name" . }}-secure"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.dnsName }}`)
    kind: Rule
    services:
    - name: {{ template "tkf-docker-calibre-web.fullname" . }}
      port: 8083
  tls:
    secretName: ebooks-svcs-teknofile-space-tls
