{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "tkf-docker-calibre-web.name" . }}-library
  labels:
    app: {{ template "tkf-docker-calibre-web.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  nfs:
    path: {{ .Values.nfs.libraryPath }}
    server: {{ .Values.nfs.libraryServer }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ template "tkf-docker-calibre-web.name" . }}-library
{{- end }}
{{- end }}
