apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-calibre-web.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: tkf-docker-calibre-web
