apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-calibre-web.fullname" . }}
  labels:
    {{- include "tkf-docker-calibre-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "tkf-docker-calibre-web.selectorLabels" . | nindent 4 }}
