apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkf-docker-openldap.fullname" . }}
  labels:
    {{- include "tkf-docker-openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 636
      protocol: TCP

  selector:
    {{- include "tkf-docker-openldap.selectorLabels" . | nindent 4 }}
